name: Build Gateway Image

on:
  push:
    paths:
      - "gateway/**"
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          context: gateway
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/self-hosted-gateway:latest
            ghcr.io/${{ github.repository_owner }}/self-hosted-gateway:${{ github.sha }}
